// Generated by CoffeeScript 1.3.3
(function() {

  this.TodoController = function($scope) {
    $scope.todos = [
      {
        text: 'learn angular',
        done: true
      }, {
        text: 'build an angular app',
        done: false
      }
    ];
    $scope.addTodo = function() {
      $scope.todos.push({
        text: $scope.todoText,
        done: false
      });
      return $scope.todoText = '';
    };
    $scope.remaining = function() {
      return $scope.todoFilter($scope.todos, false).length;
    };
    $scope.todoFilter = function(todos, status) {
      var todo, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = todos.length; _i < _len; _i++) {
        todo = todos[_i];
        _results.push((function(todo) {
          if (todo.done === status) {
            return todo;
          }
        })(todo));
      }
      return _results;
    };
    return $scope.archive = function() {
      var inPogressTodos, todo, _i, _len, _results;
      inPogressTodos = $scope.todos;
      $scope.todos = [];
      _results = [];
      for (_i = 0, _len = inPogressTodos.length; _i < _len; _i++) {
        todo = inPogressTodos[_i];
        _results.push((function(todo) {
          if (todo.done === false) {
            return $scope.todos.push(todo);
          }
        })(todo));
      }
      return _results;
    };
  };

}).call(this);
